name: computingPracticum
version: 0.1.0.0
github: "KubEF/computingPracticum"
license: BSD-3-Clause
author: "Kubishkin Efim"
maintainer: "efimkub@mail.ru"
copyright: "2023 Kubishkin Efim"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/KubEF/computingPracticum#readme>

dependencies:
  - base >= 4.7 && < 5
  - table-layout
# default-extensions:
#   - ImportQualifiedPost
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

language: GHC2021

library:
  source-dirs: src
  exposed-modules:
    - Lib
    - FirstHw.CalculateFunc
    - SecondHw.Interpolation
    - SecondHw.PrintResults
    - ThirdHw.RevInterpolation
    - ThirdHw.NumericalDiff
    - ThirdHw.PrintResults
executables:
  computingPracticum-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - computingPracticum

tests:
  computingPracticum-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - computingPracticum
